### ISSUE TITLE
Validation errors in the flows examples

### ISSUE THREAD

**Issue by chaya7908** [mnubo/node-red-contrib-mnubo#11]
When I import your [example flow](https://www.npmjs.com/package/node-red-contribmnubo#section5), and try to deploy it, I get an error dialog, the flow JSON has invalid configuration.

**mnubo config:**

```
{
    "id": "ea597271.15a69",
    "type": "mnubo config",
    "z": "2d7a2cc9.d285d4",
    "name": "Jerome",
    "env": "sandbox",
    "proxy_url": ""
}
```
When I create new `mnubo config` node, it has defaults:
```
{
    "id": "f1030bf5.281268",
    "type": "mnubo config",
    "z": "",
    "name": "",
    "env": "sandbox",
    "proxy_url": "",
    "retries": false,
    "numberOfAttempts": "5",
    "initialDelayInMillis": "500"
}
```
When `numberOfAttempts` and `initialDelayInMillis` are missing, config node has validation error, because they have to be numbers and can't be `undefined`.

**nmubo events:**
```
{
    "id": "9f0aed7.f60f51",
    "type": "mnubo events",
    "z": "2d7a2cc9.d285d4",
    "name": "",
    "mnuboconfig": "ea597271.15a69",
    "functionselection": "send",
    "inputtext": "",
    "x": 469,
    "y": 481,
    "wires": [
        ["f3f191c9.0c0e7"]
    ]
}
```
When I drag new `mnubo events` node, it has defaults:
```
{
    "id": "e207dba3.006978",
    "type": "mnubo events",
    "z": "150a77db.1bdb58",
    "name": "",
    "mnuboconfig": "",
    "functionselection": "send",
    "inputtext": "",
    "reportResults": false,
    "objectsMustExist": false,
    "x": 840,
    "y": 620,
    "wires": [
        []
    ]
}
```
When `reportResults` and `objectsMustExist` are missing, I get error when I try to inject the flow,
I get error: `The query parameter 'objects_must_exist' was malformed:
'undefined' is not a valid Boolean value`

I think the example is not completely up to date.

**Comment by DiegoAntonino** [comment]
Hi, 
I could not reproduce none of these errors. 

I have test this example:

`[{"id":"ea597271.15a69","type":"mnubo config","z":"2d7a2cc9.d285d4","name":"Jerome","env":"sandbox","proxy_url":""},{"id":"17925606.e86daa","type":"mnubo auth","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","x":440,"y":56,"wires":[["561a8d39.a9e574"]]},{"id":"51b613ce.ae49ec","type":"inject","z":"2d7a2cc9.d285d4","name":"","topic":"Test All","payload":"","payloadType":"none","repeat":"","crontab":"","once":false,"x":95,"y":63,"wires":[["17925606.e86daa"]]},{"id":"e6b03005.194fd","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":924,"y":194,"wires":[]},{"id":"561a8d39.a9e574","type":"switch","z":"2d7a2cc9.d285d4","name":"Token != Bearer","property":"payload.token_type","rules":[{"t":"neq","v":"Bearer"},{"t":"eq","v":"Bearer"}],"checkall":"true","outputs":2,"x":646,"y":57,"wires":[["edd7671.f122898"],["9e5aef3.f61a51","7638564f.89c7a8"]]},{"id":"5aa31777.a55ce8","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":925,"y":163,"wires":[]},{"id":"9bbadf79.64452","type":"mnubo owners","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","functionselection":"create","inputtext":"","x":495,"y":169,"wires":[["cef1f5b4.310e08"]]},{"id":"dedbc5dd.212438","type":"mnubo owners","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","functionselection":"delete","inputtext":"","x":487,"y":845,"wires":[["20e69541.df196a"]]},{"id":"cef1f5b4.310e08","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":684,"y":170,"wires":[["5aa31777.a55ce8"],["e6b03005.194fd","8c56464e.73a9b8"]]},{"id":"edd7671.f122898","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":932,"y":44,"wires":[]},{"id":"9e5aef3.f61a51","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":930,"y":76,"wires":[]},{"id":"e27db47b.1d8248","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":916,"y":838,"wires":[]},{"id":"826e9923.7d9168","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":913,"y":870,"wires":[]},{"id":"5d93e52a.a26c1c","type":"inject","z":"2d7a2cc9.d285d4","name":"","topic":"clean","payload":"node-red-auto1@test.com","payloadType":"none","repeat":"","crontab":"","once":false,"x":90,"y":845,"wires":[["26751614.d98aea"]]},{"id":"8b0cf49c.74f308","type":"inject","z":"2d7a2cc9.d285d4","name":"","topic":"","payload":"","payloadType":"none","repeat":"","crontab":"","once":false,"x":104,"y":115,"wires":[["7638564f.89c7a8"]]},{"id":"20e69541.df196a","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":707,"y":840,"wires":[["e27db47b.1d8248"],["826e9923.7d9168"]]},{"id":"2d1551a5.d2eaae","type":"mnubo owners","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","functionselection":"update","inputtext":"","x":485,"y":244,"wires":[["1ac7224c.e538de"]]},{"id":"2613a0df.d9ec6","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":924,"y":268,"wires":[]},{"id":"9a919985.656e68","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":924,"y":236,"wires":[]},{"id":"1ac7224c.e538de","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":754,"y":243,"wires":[["9a919985.656e68"],["2613a0df.d9ec6","59891fad.a676e"]]},{"id":"160827c6.e9f7d8","type":"mnubo objects","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","functionselection":"create","inputtext":"","x":484,"y":329,"wires":[["aecec38f.51314"]]},{"id":"aecec38f.51314","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":689,"y":328,"wires":[["7693bc16.896c44"],["5541f356.aabe0c","f6a1d851.095e28"]]},{"id":"7693bc16.896c44","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":923,"y":315,"wires":[]},{"id":"5541f356.aabe0c","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":923,"y":347,"wires":[]},{"id":"888d985f.777268","type":"mnubo objects","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","functionselection":"delete","inputtext":"","x":483,"y":767,"wires":[["c1c10f87.3e3ef"]]},{"id":"520a783b.adf588","type":"inject","z":"2d7a2cc9.d285d4","name":"","topic":"clean","payload":"node-red-auto1@test.com","payloadType":"none","repeat":"","crontab":"","once":false,"x":91,"y":769,"wires":[["a4cc7ee4.5b338"]]},{"id":"21ddd627.de222a","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":919,"y":747,"wires":[]},{"id":"118809d1.ee77f6","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":918,"y":779,"wires":[]},{"id":"c1c10f87.3e3ef","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":709,"y":757,"wires":[["21ddd627.de222a"],["118809d1.ee77f6","26751614.d98aea"]]},{"id":"bc053e9.f43fac","type":"mnubo objects","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","functionselection":"update","inputtext":"","x":474,"y":405,"wires":[["37638d74.c89c72"]]},{"id":"c1ce8353.3e318","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":921,"y":424,"wires":[]},{"id":"9dbfbc60.62404","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":921,"y":392,"wires":[]},{"id":"37638d74.c89c72","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":743,"y":405,"wires":[["9dbfbc60.62404"],["c1ce8353.3e318","ef9f73c3.10609"]]},{"id":"9f0aed7.f60f51","type":"mnubo events","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","functionselection":"send","inputtext":"","x":469,"y":481,"wires":[["f3f191c9.0c0e7"]]},{"id":"f45df5fa.0ba208","type":"mnubo events","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","functionselection":"sendfromdevice","inputtext":"[\n    \"node-red-device-auto1\", \n    [{\n\t\"x_event_type\": \"event_type_test\",\n\t\"x_timestamp\": \"2015-01-22T00:01:25-02:00\",\n\t\"x_latitude\": 57.876,\n\t\"x_longitude\": 57.876,\n\t\"temperature\": 15.2\n    }]\n]","x":522.5555572509766,"y":558.1110897064209,"wires":[["59c45d43.a63ba4"]]},{"id":"70b1e62a.8f4e18","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":922,"y":501,"wires":[]},{"id":"154891fb.eab76e","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":922,"y":469,"wires":[]},{"id":"f3f191c9.0c0e7","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":749,"y":483,"wires":[["154891fb.eab76e"],["70b1e62a.8f4e18","25c970e1.da369"]]},{"id":"bd682dca.4297d","type":"debug","z":"2d7a2cc9.d285d4","name":"OK","active":true,"console":"false","complete":"payload","x":920,"y":584,"wires":[]},{"id":"15ccba17.ea3346","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":920,"y":552,"wires":[]},{"id":"59c45d43.a63ba4","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":742,"y":559,"wires":[["15ccba17.ea3346"],["bd682dca.4297d","88f33cd9.770cc"]]},{"id":"30375974.cfc8a6","type":"mnubo analytics","z":"2d7a2cc9.d285d4","name":"","mnuboconfig":"ea597271.15a69","searchtype":"SearchQuery","inputquery":"","x":459,"y":658,"wires":[["cb2aaf90.34d55","a4cc7ee4.5b338"]]},{"id":"da542530.25abd8","type":"debug","z":"2d7a2cc9.d285d4","name":"Error","active":true,"console":"false","complete":"payload","x":920,"y":635,"wires":[]},{"id":"d55b7326.2aa49","type":"debug","z":"2d7a2cc9.d285d4","name":"rows","active":true,"console":"false","complete":"payload.rows","x":920,"y":667,"wires":[]},{"id":"cb2aaf90.34d55","type":"switch","z":"2d7a2cc9.d285d4","name":"errorCode is not null","property":"payload.errorCode","rules":[{"t":"nnull"},{"t":"null"}],"checkall":"true","outputs":2,"x":705,"y":656,"wires":[["da542530.25abd8"],["d55b7326.2aa49"]]},{"id":"2be4304.fd41bd","type":"function","z":"2d7a2cc9.d285d4","name":"Create Owner","func":"msg.payload =\n{\n\t\"username\": context.global.mnubo.owner1,\n\t\"x_password\": \"12345678\"\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":319.4444694519043,"y":167.88886642456055,"wires":[["9bbadf79.64452"]]},{"id":"59891fad.a676e","type":"function","z":"2d7a2cc9.d285d4","name":"Create an Object","func":"msg.payload = {\n\t\"x_device_id\": context.global.mnubo.object1,\n\t\"x_object_type\": \"test\",\n\t\"x_owner\": {\n\t\t\"username\": context.global.mnubo.owner1\n\t}\n};\nreturn msg;","outputs":1,"noerr":0,"x":289.4444465637207,"y":330.11110496520996,"wires":[["160827c6.e9f7d8"]]},{"id":"ef9f73c3.10609","type":"function","z":"2d7a2cc9.d285d4","name":"Send an event","func":"msg.payload = [{\n\t\"x_object\": {\"x_device_id\": context.global.mnubo.object1},\n\t\"x_event_type\": \"event_type_test\",\n\t\"x_timestamp\": \"2015-01-22T00:01:25-02:00\",\n\t\"x_latitude\": 57.876,\n\t\"x_longitude\": 57.876,\n\t\"temperature\": 25.6\n}];\nreturn msg;","outputs":1,"noerr":0,"x":276.11113357543945,"y":483.44441986083984,"wires":[["9f0aed7.f60f51"]]},{"id":"88f33cd9.770cc","type":"function","z":"2d7a2cc9.d285d4","name":"Count Events","func":"msg.payload = {\n\t\"from\": \"event\",\n\t\"select\": [{\n\t\t\"count\": \"*\"\n\t}]\n};\nreturn msg;","outputs":1,"noerr":0,"x":227.22222518920898,"y":660.1111354827881,"wires":[["30375974.cfc8a6"]]},{"id":"8c56464e.73a9b8","type":"function","z":"2d7a2cc9.d285d4","name":"Update owner","func":"msg.payload = [ \n  context.global.mnubo.owner1, \n  { \n\t\"x_registration_latitude\": 45.223, \n\t\"x_registration_longitude\": 73.234 \n  }\n];\nreturn msg;","outputs":1,"noerr":0,"x":289.44443130493164,"y":245.6666488647461,"wires":[["2d1551a5.d2eaae"]]},{"id":"f6a1d851.095e28","type":"function","z":"2d7a2cc9.d285d4","name":"Update Object","func":"msg.payload = [\n    context.global.mnubo.object1, \n{ \n\t\"x_object_type\": \"test2\" \n}\n];\nreturn msg;\n","outputs":1,"noerr":0,"x":286.11111068725586,"y":406.7777976989746,"wires":[["bc053e9.f43fac"]]},{"id":"25c970e1.da369","type":"function","z":"2d7a2cc9.d285d4","name":"Send an Event FROM the object","func":"msg.payload = [\n    context.global.mnubo.object1, \n    [{\n\t\"x_event_type\": \"event_type_test\",\n\t\"x_timestamp\": \"2015-01-22T00:01:25-02:00\",\n\t\"x_latitude\": 57.876,\n\t\"x_longitude\": 57.876,\n\t\"temperature\": 15.2\n    }]\n];\n\nreturn msg;","outputs":1,"noerr":0,"x":254.33331298828125,"y":540.7777709960938,"wires":[["f45df5fa.0ba208"]]},{"id":"7638564f.89c7a8","type":"function","z":"2d7a2cc9.d285d4","name":"set global env","func":"var mnubo = new Object();\nmnubo.owner1 = \"node-red-auto1@test.com\"\nmnubo.object1 = \"node-red-device-auto1\"\n\n//Global context share by all functions\ncontext.global.mnubo = mnubo\n\nreturn msg;","outputs":1,"noerr":0,"x":327,"y":116,"wires":[["2be4304.fd41bd"]]},{"id":"26751614.d98aea","type":"function","z":"2d7a2cc9.d285d4","name":"delete owner1","func":"msg.payload = context.global.mnubo.owner1\nreturn msg;","outputs":1,"noerr":0,"x":267,"y":848,"wires":[["dedbc5dd.212438"]]},{"id":"a4cc7ee4.5b338","type":"function","z":"2d7a2cc9.d285d4","name":"delete owner1","func":"msg.payload = context.global.mnubo.object1\nreturn msg;","outputs":1,"noerr":0,"x":265,"y":769,"wires":[["888d985f.777268"]]},{"id":"a23c57f8.5dc3a8","type":"inject","z":"2d7a2cc9.d285d4","name":"","topic":"","payload":"","payloadType":"none","repeat":"","crontab":"","once":false,"x":88,"y":169,"wires":[["2be4304.fd41bd"]]}]`

Using a right mnubo-config (Client Id/Client Secret) (please use the one you used before)
Node-RED version: v0.17.4
Node.js  version: v6.11.0
mnubo-sdk version: 1.10.0
node-red-contrib-mnubo version: 1.3.3

Also, **numberOfAttempts**, **initialDelayInMillis**, **reportResults** and **objectsMustExist** are set with a default values.

Could you please let me know if you are using a different version?

Diego

**Comment by daddykotex** [comment]
I could reproduce because I started from scratch. I copied the available in the npm doc of node-red-contrib-mnubo and I successfully reproduced the error. The example flow is out of date and has no value for `reportResults` and `objectsMustExist`.

I've opened a PR that fixes the issue: https://github.com/mnubo/node-red-contrib-mnubo/pull/12

**Comment by daddykotex** [comment]
With that said, the example flow should be updated.

**Comment by DiegoAntonino** [comment]
Fixed all these validations.

You can find latest version (node-red-contrib-mnubo@1.3.7) published on NPM.
Thanks!
