### ISSUE TITLE
Missing Unit Tests

### ISSUE THREAD

**Issue by chaya7908** [mnubo/node-red-contrib-mnubo#4]
We want to use your code, but unfortunately, we didn't see any Unit Tests for it.
Can you add it, please?

**Comment by jtheoof** [comment]
Hi @chaya7908, this project heavily relies on [smartobjects-js-client)(https://github.com/mnubo/smartobjects-js-client) which is unit tested with Jasmine. This should help you understand the usage for the SmartObjects platform through our JS client. Is there something you'd like to see in addition to that? I had a quick look around at different node-red projects but they don't seem to have unit tests either. Perhaps we could clarify the documentation.

**Comment by chaya7908** [comment]
Hi @jtheoof, Thanks for your answer,
Node-Red nodes have [tests](https://github.com/node-red/node-red/tree/master/test/nodes),
Also other Node-Red nodes libraries have tests for the nodes, for example [modbus](https://github.com/biancode/node-modbus/tree/master/test) [chatbot](https://github.com/guidone/node-red-contrib-chatbot/tree/master/test), [cache-node](https://github.com/CANDY-LINE/node-red-contrib-cache/tree/master/tests) etc.
We need tests for the **nodes**, so it will not take down our coverage.

**Comment by jtheoof** [comment]
Could you describe a bit your use case? I'm trying to understand how using a third party node impacts your own code coverage. Usually code coverage requires a specific testing library and in the examples you sent there is no status quo, some use mocha, others sinon, ...
Here you don't seem to request a particular testing framework.

**Comment by jtheoof** [comment]
@chaya7908 we've published version `1.3.1` of the the package. You should be good to go.
